export const SET_MEALS = 'SET_MEALS';
export const ADD_MEAL = Object.freeze({
	START: 'ADD_MEAL_START',
	FINISH: 'ADD_MEAL_FINISH',
	ERROR: 'ADD_MEAL_ERROR'
});
export const UPDATE_MEAL = 'UPDATE_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';

export const SET_USER = 'SET_USER';

export const SET_MEMBER = 'SET_MEMBER';
export const SET_MEMBERS = 'SET_MEMBERS';
export const ADD_MEMBER = Object.freeze({
	START: 'ADD_MEMBER_START',
	FINISH: 'ADD_MEMBER_FINISH',
	ERROR: 'ADD_MEMBER_ERROR'
});
export const DELETE_MEMBER = 'DELETE_MEMBER';

export const AUTH_USER = Object.freeze({
	START: 'AUTH_USER_START',
	FINISH: 'AUTH_USER_FINISH',
	ERROR: 'AUTH_USER_ERROR',
});
export const UNAUTH_USER = Object.freeze({
	START: 'UNAUTH_USER_START',
	FINISH: 'UNAUTH_USER_FINISH',
	ERROR: 'UNAUTH_USER_ERROR',
});

export const CREATE_USER = Object.freeze({
	START: 'CREATE_USER_START',
	FINISH: 'CREATE_USER_FINISH',
	ERROR: 'CREATE_USER_ERROR',
});
